# Generated by Django 6.1.1 on 2026-09-29 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='account/photos/', verbose_name='Фото'),
        ),
    ]
