# Generated by Django 6.1.1 on 2026-10-04 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True, verbose_name='Слово')),
                ('language', models.CharField(choices=[('en', 'English'), ('ru', 'Russian')], max_length=2, verbose_name='Язык')),
                ('part_of_speech', models.CharField(choices=[('noun', 'существительное'), ('verb', 'глагол'), ('adjective', 'прилагательное'), ('adverb', 'наречие'), ('pronoun', 'местоимение'), ('preposition', 'предлог'), ('conjunction', 'союз'), ('numeral', 'числительное'), ('interjection', 'междометие')], max_length=16, verbose_name='Часть речи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='words', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('translations', models.ManyToManyField(blank=True, to='words.word', verbose_name='Переводы')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='AccountWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'В процессе изучения'), ('learned', 'Изучено')], max_length=16, verbose_name='Статус')),
                ('count_error', models.IntegerField(default=0, verbose_name='Количество ошибок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_words', to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_words', to='words.word', verbose_name='Слово')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('account', 'word'), name='unique_account_word')],
            },
        ),
    ]
